import {NextPage} from "next";
import {api} from "~/utils/api";
import Head from "next/head";

const Home: NextPage = () => {
    // const hello = api.example.hello.useQuery({ text: "from tRPC" });

    return (
        <>
            <Head>
                <title>Curriculum vitae</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#450a0a] to-[#991b1b]">
                <div>

                </div>
            </main>
        </>
    );
};

export default Home;